#ifndef QTSCRIPTLUAGLOBAL_H
#define QTSCRIPTLUAGLOBAL_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

#ifndef QT_STATIC
#  if defined(QT_BUILD_SCRIPTLUA_LIB)
#    define Q_SCRIPTLUA_EXPORT Q_DECL_EXPORT
#  else
#    define Q_SCRIPTLUA_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_SCRIPTLUA_EXPORT
#endif

QT_END_NAMESPACE

#endif // QTSCRIPTLUAGLOBAL_H
